### PR TITLE
feat: added typescript support and definitions + some validation

### PR DESCRIPTION
**Pull request by KarolNov**
In order to test out if I can use this repo as boilerplate for my purpose I played around with adding TS + some basic validation. This PR contains results of my work.

### CODE REVIEW

**Comment by samuelkraft** [comment]
Hi @KarolNov, thanks for the PR! Sorry for the slow response here, I've been debating whether adding typescript is a good idea or not for this repo due to added complexity for beginners. I want to keep the repo accessible to new devs and that was the main reason it was not added in the beginning. 
After giving it some thought I think the benefits outweighs the potential complexity. Would you mind solving the outstanding conflict so I can merge this?
Thanks

**Comment by KarolNov** [comment]
@samuelkraft I guess that make sense and the typings I did are quite complicated (I use different built-in magic methods like `Extract`) and might be confusing for beginners. I wonder what's the best solution here, but I'm planning to build an open source CMS engine for Notion using Typescript, so I guess once that's published anyone interested in Typescript version can go and find it. If you still think it's worth it I can resolve the conflict when I'll have some spare time.

**Review by elwynynion — COMMENTED** [review]
test

**Comment by samuelkraft** [comment]
Closing this to focus on the basic js implementation

**Pull request closed without merging**
